apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs-test-vol01
spec:
capacity:
   storage: 1Gi
accessModes:
   - ReadWriteMany
persistentVolumeReclaimPolicy: Recycle
nfs:
   path: /storage
   server: r75-nfs01.csplab.local
