---
# Description:
#   Install nfs-utils on the target nodes.
#
# INPUTS:
#   vars:
#     target_nodes - a regex string or group name that defines the nodes or
#                    node group on which nfs-utils should be started.
#
#     You can define the vars on the ansible-playbook command line using --extra-vars.
#     Or define vars in your hosts inventory or any of the other ways to define
#     Ansible variables.
#     The --inventory option can be used to provide a path to an inventory file
#     on the ansible-playbook command line.
#
# Root privilege is needed to install nfs-utils.
# The tasks where root is needed use the "become" option.
#
# Sample invocation:
#   ansible-playbook install-nfs-utils.yaml --extra-vars "target_nodes=worker0*"
#

- hosts: "{{ target_nodes }}"

  tasks:
    - name: Install NFS Utilities
      package:
        name: nfs-utils
        state: present
      become: True

...
